# 3D Reconstruction
Now that we have the silhuettes we can now extract the visual hull of the object. Do so we need the camera intrinsic parameters and the extrinsic paramters. Our simulation pipeline already provides us with a json file for that.

In [16]:
import json

import numpy as np

In [ ]:
class CamerasData:
    def __init__(self, intrinsic_path: str, extrinsic_path: str):
        # Store the paths
        self.intrinsic_path = intrinsic_path
        self.extrinsic_path = extrinsic_path

        # extract the json data
        self.intrinsic_data, self.extrinsic_data = self.load_data()

        # unpack the transformation matrices
        self.extrinsic_matrices = self.extract_extrinsic_matrices()

    def load_data(self) -> tuple[dict, dict]:
        with open(self.intrinsic_path, 'r') as f:
            intrinsic_data = json.load(f)
        with open(self.extrinsic_path, 'r') as f:
            extrinsic_data = json.load(f)
        return (intrinsic_data, extrinsic_data)

    def extract_extrinsic_matrices(self) -> np.ndarray:
        # Unpacks the data from the json file into a numpy array
        array_data = self.extrinsic_data["frames"]
        transformation_matrices = []

        # Loop over each camera and extract the transformation matrix
        for cam in array_data:
            matrix_data = np.array(cam["transform_matrix"])
            transformation_matrices.append(matrix_data)

        # Convert to a numpy array
        return np.array(transformation_matrices)

In [55]:
camera_data = CamerasData("../blender_simulator/simulated_frames/dataset_d30/transforms_train.json", "../blender_simulator/simulated_frames/dataset_d30/transforms_train.json")

In [ ]:
trf_mt = camera_data.extract_extrinsic_matrices()

In [52]:
len(trf_mt)

12

In [53]:
trf_mt[0]

array([[ 9.99992847e-01,  5.45056282e-05,  3.79700959e-03,
         0.00000000e+00],
       [ 3.79740074e-03, -1.43533014e-02, -9.99889851e-01,
        -1.00000000e+00],
       [-3.63797881e-12,  9.99897003e-01, -1.43534066e-02,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [ ]:
camera_data.extrinsic_matrices

[array([[ 9.99992847e-01,  5.45056282e-05,  3.79700959e-03,
          0.00000000e+00],
        [ 3.79740074e-03, -1.43533014e-02, -9.99889851e-01,
         -1.00000000e+00],
        [-3.63797881e-12,  9.99897003e-01, -1.43534066e-02,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[ 8.61065686e-01, -7.28784548e-03, -5.08441567e-01,
         -4.99882162e-01],
        [-5.08493781e-01, -1.23409843e-02, -8.60977232e-01,
         -8.65877032e-01],
        [-4.65661287e-10,  9.99897361e-01, -1.43322209e-02,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[ 0.48193851, -0.01245331, -0.87611651, -0.86587703],
        [-0.87620503, -0.00684969, -0.48188984, -0.49988216],
        [ 0.        ,  0.99989909, -0.01421278,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-2.57461872e-02, -1.40279029e-02, -9.9957